Global Refactoring
htmlacademy-ecmascript/1510239-big-trip-12 pull request #17
Opened 2020-09-10 18:06 UTC by kornilow-d

2020-09-12 18:21 UTC, Sergey-Rozhkov requested changes
см комменты

2020-09-12 18:21 UTC, Sergey-Rozhkov commented on src/utils/date.js
> +  return moment(date).format(`YYYY-DD-MM`);
формат вынести в константу

2020-09-12 18:21 UTC, Sergey-Rozhkov commented on src/utils/date.js
> +  return moment(time).format(`HH:mm`);
формат вынести в константу

2020-09-12 18:21 UTC, Sergey-Rozhkov commented on src/utils/date.js
> +  .join(` `);
это всё можно заменить на один редьюс

2020-09-12 18:21 UTC, Sergey-Rozhkov commented on src/utils/date.js
> +  const duration = moment.duration(interval);
Если подключил момент, было бы неплохо не изобретать велосипед а добавить `moment-duration-format`

2020-09-12 18:21 UTC, Sergey-Rozhkov commented on src/utils/date.js
> +  return moment(time).format(`DD/MM/YY HH:mm`);
формат в шаблон

2020-09-12 18:21 UTC, Sergey-Rozhkov commented on src/utils/filter.js
> +  }),
```suggestion
  [FilterType.FUTURE]: (points) => points.filter((point) => moment(point.timeStart).isAfter(new Date(), `day`)),
  [FilterType.PAST]: (points) => points.filter((point) => moment(point.timeStart).isBefore(new Date(), `day`)),
```

2020-09-12 18:21 UTC, Sergey-Rozhkov commented on src/view/statistics.js
> +    }
Дублирование ?

2020-09-12 18:21 UTC, Sergey-Rozhkov commented on src/view/statistics.js
> +    const BAR_HEIGHT = 55;
Константу стоит определять вне модуля

2020-09-12 18:21 UTC, Sergey-Rozhkov commented on src/view/statistics.js
> +    timeSpendCtx.height = BAR_HEIGHT * 4;
Магические 4 и 6 вынести в константы

2020-09-12 18:21 UTC, Sergey-Rozhkov commented on src/view/statistics.js
> +        if (transportTypes.includes(point.type)) {
```suggestion
      } else  if (transportTypes.includes(point.type)) {
```

2020-09-12 18:21 UTC, Sergey-Rozhkov commented on src/view/statistics.js
> +    }, {});
Сложная логика и не читаемый код

2020-09-13 06:35 UTC, kornilow-d commented on src/main.js
> +const filtersHeaderNode = headerNode.querySelectorAll(`.trip-controls h2`)[1];
Поправил, добавил служебные классы, прицепился к ним

2020-09-13 06:36 UTC, kornilow-d commented on src/main.js
> +const newPointButton = headerNode.querySelector(`.trip-main__event-add-btn`);
Поправил

2020-09-13 06:37 UTC, kornilow-d commented on src/main.js
> +      statisticsPresenter.init();
Так там всего 3 кнопки. Что можно прописать в дефолт? У меня на ум приходит только return

2020-09-13 07:05 UTC, kornilow-d commented on src/mock/offers.js
> +  return offers;
Не совсем понимаю как

2020-09-13 07:06 UTC, kornilow-d commented on src/view/statistics.js
> +    const BAR_HEIGHT = 55;
Поправил

2020-09-13 07:10 UTC, kornilow-d commented on src/view/statistics.js
> +    timeSpendCtx.height = BAR_HEIGHT * 4;
поправил

2020-09-13 07:10 UTC, kornilow-d commented on src/view/statistics.js
> +        if (transportTypes.includes(point.type)) {
Поправил

2020-09-13 07:55 UTC, kornilow-d commented on src/view/statistics.js
> +    }
Поправил

2020-09-13 12:12 UTC, Sergey-Rozhkov commented on src/main.js
> +      statisticsPresenter.init();
Ну например не то значение передашь
На консультации расскажу

2020-09-13 12:13 UTC, Sergey-Rozhkov commented on src/mock/offers.js
> +  return offers;
На консультации

2020-09-13 12:13 UTC, merged